### PR TITLE
Restructure levels and images and introduce quality assurance guidelines

### PR DESCRIPTION
**Pull request by Wuzzy2**
This **extreme** PR basically does what I have requested in #167 (level quality assurance).

First, I have moved A LOT of images to `imagery`.
Then I have moved most levels into new folders, as suggested.
Then I have made a ton of quality assurance work on the levels that needed polishing.
Most work to make a level “finished” revolved around:

* Making sure ALL custom objects get a tooltip
* Preferring default objects over custom ones
* Fixing typos, grammar and typography
* Fixing/cleaning up other minor problems

After that I also have tested and moved a lot of levels to `finished`, based on the criteria listed in that issue.
Lastly, I added a text file (`levels/QUALITY-ASSURANCE`) explaining the new conventions.
My QA work is NOT intended to be a single task, but a continous way of managing levels. This is what I want to establish.

I am now going to list those levels which have _not_ made it into `finished` yet:

List of levels in `draft`:
* 99luftballons
* wasteofcola
* wedge_land

List of levels in `needs-polishing` (and a reason (non-exhaustive) why it is not in finished yet):

* 001: flower (since this is a custom object with missing tooltip)
* 002: flower
* 004: pyramid looks ugly and does not have a tooltip
* 007: flower
* 10_kilograms_above_the_ground: flower
* ballons-do-poof: flower, goal (the object)
* bowling-pin-plays-soccer: goal
* brother-plays-soccer: goal, flower
* brother-plays-penguin-goalie: goal
* butterfly_race: flower
* butterfly-on-steroids: flower
* cola_reaction: needs visible guard rail for the peg
* dialbforboom: blue dominoes can still be destroyed by hard bowling ball collision alone. 
* extreme-tux-racer: goal
* find-the-message.v2: flower
* geyser: green fake floor is weird
* goal-maker: goal
* hattrick: goal
* imperfectbalance: flower
* loopings2: goal
* party-at-office: missing tooltip for Jumping Jack. Currently not possible for jj-body, since it is scenery and tooltips for scenery are not supported
* picnic-2: tooltip for sand, sand uses a really, really ugly hack (uses invisible tennis balls)
* poofpoofpoof: post-it text seems inappropriate/misleading/confusing. Is there a reason for this? otherwise fine
* save-the-butterfly: flower
* spare-the-balloon: goal
* styrofoam: goal
* zoingandboom: level is not reliable enough for my taste

As you see, many levels have custom flower or goal objects. I want to keep these levels in `needs-polishing` until “real” goal or flower objects exist, so the custom objects can be replaced.
I think I could make an issue of this list later.

All other levels are in `finished`, `test` or `attic`.

I have tested ALL levels and their imagery to make sure I didn't break anything. Levels in `finished` even more so. But feel free to test for yourselves, just to be sure. After all, this PR touches almost everything.

Downside of this PR: Old save states are going to be useless with the next version, since TBE only remembers the full level path. Since the level paths have changed, TBE won't recognize the levels as solved or skipped anymore.
Maybe as an follow-up issue, we could try to work out a better way how TBE saves solved levels. This won't probably the last time the levels change directories.

### CODE REVIEW

**Comment by kaa-ching** [comment]
I want to merge this issue early, but it currently has conficts. 
Probably my doing: after all I renamed the Pingus object.

@Wuzzy2 : are you going to pick up merging the latest changes in or do you want me to do it?

**Comment by Wuzzy2** [comment]
Well, I try to do the merging by myself today. You will hear from my if I have finished it or have problems.

**Comment by Wuzzy2** [comment]
The merge is done.
Funny, the merge was trivial, there were actually no conflicts. :-)

**Comment by kaa-ching** [comment]
I'd like to add one more requirement for levels in `finished`: get hints (if possible, e.g. setting phone numbers is not yet possible).

**Pull request merged**
