### PR TITLE
Show cursor coordinates in level creator

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR adds a status bar which currently has only one purpose: Showing the coordinates of the cursor in the current level. I think this simple addition makes editing a lot easier, especially for finding the correct coordinates for goals.

The status bar is hidden in the normal game since it is of no use here.

Maybe other stuff (debugging things) could be added later.

### CODE REVIEW

**Comment by kaa-ching** [comment]
There's good and bad things about this patch.

Good:
 * Thanks for the patch! You solve your own feature request!
 * You use the QStatusBar class as it is already part of QMainWindow!
 * You immediately set a separate widget for the coordinates

Bad:
 * there shouldn't be a need to call statusBar() in the initialization
 * you shouldn't need to `#include "Position.h` in resizinggraphicsview.h
 * you leak a private pointer from MainWindow to the ResizingGraphicsView
 * in the ResizingGraphicsView, you add a widget to that pointer which is not owned by MainWindow
 * you didn't declare the mouseMoveEvent() to be a slot
 
I would do it like this:
 * in ResizingGraphicsView::mouseMoveEvent(), emit the update to a new slot in MainWindow
 * let that slot in MainWindow do the work, let MainWindow keep ownership of the Label.

**Comment by kaa-ching** [comment]
@Wuzzy2 ? any updates? This fix impacts the translation strings, so if we want this in Milestone B, you have to hurry!

**Comment by Wuzzy2** [comment]
Currently working on this.
Give me 3 hours, if I don't make it in that time, I won't mind if you move this PR to the next milestone instead.

**Comment by Wuzzy2** [comment]
OK, I hope I have fixed your requests.
Except I haven't turned mouseMoveEvent to a slot because I don't see why. It seems senseless to me.
And as I already said in IRC, `statusBar()` will create the status bar if it does not exist yet (apart from returning a pointer).

**Comment by kaa-ching** [comment]
You did exactly as asked, thanks!

Too bad that in the mean time, I messed up the code, so merging will be "hell".
My problem!

**Comment by kaa-ching** [comment]
made a small change 4329417.

**Pull request merged**
