### PR TITLE
New level: Domino Flip Machine

### PR DESCRIPTION
**Pull request by Wuzzy2**
Hi! I created a new domino level for TBE.
The goal is to topple 120 dominoes. :-)

It's finished and has hints, but for some reason regression testing does not work. The pivot point of the rotating bars seems to screw up. Otherwise, this level looks fine to me. The only thing which kept me from adding this to `finished` right away were the broken hints.

---
Note the file size is unusually large (for a level) since the level file contains 120 goal conditions, one for each domino. xD The IDs and goals were added by scripting, so I am pretty sure I haven't missed any domino.
Making this level was pretty tedious, to be honest. This probably explains why there aren't many domino levels in this game so far. :-(

### CODE REVIEW

**Comment by kaa-ching** [comment]
I've merged the level and added it to the google doc with all level ratings. I like this level and I see your pain with creating all of it. 

You could have cheated by only listing goals for the left and right dominoes from each set?

**Comment by lspacenl** [comment]
Wuzzy, you have been busy
Looks nice and mysterious, can't wait to get my hands on it.
What polish do you think it needs?

**Comment by Wuzzy2** [comment]
> What polish do you think it needs?

Basically it's only the hints because they don't really work but I guess this is because of the engine. Not sure if hints are a hard requirement now. If you think the level is OK, feel free to move it to `finished` then. ;-)

**Comment by kaa-ching** [comment]
Once the new toolbox is fully done and the old code is removed, I'll update the hints mechanism. 

It probably will require manually changing all hints afterwards :unamused:

**Pull request merged**
